# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - 5432:5432
  redis:
    image: 'bitnami/redis:6.0.8'
    environment:
      REDIS_PASSWORD: password123
    ports:
    - 6379:6379